import type { FastifyInstance } from 'fastify';
import type { Container } from './container.js';
import { registerHealthModule } from '../modules/health/health.module.js';
import { registerNewslettersModule } from '../modules/newsletters/newsletters.module.js';
import { registerAuthModule } from '../modules/auth/auth.module.js';
import { registerUsersModule } from '../modules/users/users.module.js';
import { registerCategoriesModule } from '../modules/categories/categories.module.js';
import { registerBrandsModule } from '../modules/brands/brands.module.js';
import { registerMediaModule } from '../modules/media/media.module.js';
import { registerInventoryModule } from '../modules/inventory/inventory.module.js';
import { registerProductVariantsModule } from '../modules/product-variants/product-variants.module.js';
import { registerSettingsModule } from '../modules/settings/settings.module.js';
import { registerAddressesModule } from '../modules/addresses/addresses.module.js';
import { registerCartsModule } from '../modules/carts/carts.module.js';
import { registerOrdersModule } from '../modules/orders/orders.module.js';
import { registerPaymentsModule } from '../modules/payments/payments.module.js';
import { registerCheckoutModule } from '../modules/checkout/checkout.module.js';
import { registerShippingModule } from '../modules/shipping/shipping.module.js';
import { registerReturnsModule } from '../modules/returns/returns.module.js';
import { registerRefundsModule } from '../modules/refunds/refunds.module.js';
import { registerDiscountsModule } from '../modules/discounts/discounts.module.js';
import { registerNotificationsModule } from '../modules/notifications/notifications.module.js';
import { registerCouponsModule } from '../modules/coupons/coupons.module.js';
import { registerTaxModule } from '../modules/tax/tax.module.js';
import { registerContactModule } from '../modules/contact/contact.module.js';
import { registerAnalyticsModule } from '../modules/analytics/analytics.module.js';
import { registerAuditModule } from '../modules/audit/audit.module.js';
import { registerSearchModule } from '../modules/search/search.module.js';
import { registerWebhooksModule } from '../modules/webhooks/webhooks.module.js';
import { registerProductsModule } from '../modules/products/products.module.js';
import { registerWishlistsModule } from '../modules/wishlists/wishlists.module.js';
import { registerReviewsModule } from '../modules/reviews/reviews.module.js';
import { registerReviewPromptsModule } from '../modules/review-prompts/review-prompts.module.js';
import { registerActivityLogsModule } from '../modules/activity-logs/activity-logs.module.js';
import { registerRequestLogsModule } from '../modules/request-logs/request-logs.module.js';
import { registerEmailTemplatesModule } from '../modules/email-templates/email-templates.module.js';
import { registerSeoModule } from '../modules/seo/seo.module.js';
import { registerCommunicationsModule } from '../modules/communications/communications.module.js';
import { registerAchievementsModule } from '../modules/achievements/achievements.module.js';

export function registerRoutes(app: FastifyInstance, container: Container): void {
  registerHealthModule(container, app);
  registerNewslettersModule(container, app);
  registerAuthModule(container, app);
  registerUsersModule(container, app);
  registerCategoriesModule(container, app);
  registerBrandsModule(container, app);
  registerMediaModule(container, app);
  registerInventoryModule(container, app);
  registerProductVariantsModule(container, app);
  registerSettingsModule(container, app);
  registerAddressesModule(container, app);
  registerCouponsModule(container, app);
  registerTaxModule(container, app);
  registerSearchModule(container, app);
  registerProductsModule(container, app);
  registerCartsModule(container, app);
  registerOrdersModule(container, app);
  registerPaymentsModule(container, app);
  registerCheckoutModule(container, app);
  registerShippingModule(container, app);
  registerReturnsModule(container, app);
  registerRefundsModule(container, app);
  registerDiscountsModule(container, app);
  registerNotificationsModule(container, app);
  registerWishlistsModule(container, app);
  registerReviewsModule(container, app);
  registerContactModule(container, app);
  registerAnalyticsModule(container, app);
  registerAuditModule(container, app);
  registerWebhooksModule(container, app);
  registerReviewPromptsModule(container, app);
  registerActivityLogsModule(container, app);
  registerRequestLogsModule(container, app);
  registerEmailTemplatesModule(container, app);
  registerSeoModule(container, app);
  registerCommunicationsModule(container, app);
  registerAchievementsModule(container, app);
}
